### ISSUE TITLE
Sponza background doesn't load on Android

### ISSUE THREAD

**Issue by kenrussell** [toji/webgpu-clustered-shading#10]
With the latest Chrome Canary and WebGPU enabled in `about:flags`, the Sponza background doesn't load - not in reasonable time, at least. Haven't checked the DevTools console yet.

**Comment by toji** [comment]
Fixed in https://github.com/toji/webgpu-clustered-shading/commit/ddfc219711739688277deb5c3af5490de919af47

The Sponza scene still takes a bit to load, unfortunately. I'll see if I can't put together an even better compressed version to improve startup times.

**Comment by kenrussell** [comment]
Aha, great! Thanks for the fix.
