### ISSUE TITLE
Firefox nightly error: renderer init failed TypeError: passEncoder.end is not a function

### ISSUE THREAD

**Issue by everflux** [toji/webgpu-clustered-shading#11]
I tested with 111.0a1 (2023-01-27) (64-bit) and got the error

```
renderer init failed TypeError: passEncoder.end is not a function
    computeClusterBounds https://toji.github.io/webgpu-clustered-shading/js/webgpu-renderer/webgpu-renderer.js:580
    onResize https://toji.github.io/webgpu-clustered-shading/js/webgpu-renderer/webgpu-renderer.js:349
    resizeCallback https://toji.github.io/webgpu-clustered-shading/js/renderer.js:192
    start https://toji.github.io/webgpu-clustered-shading/js/renderer.js:229
    onApiChange https://toji.github.io/webgpu-clustered-shading/:164
    onApiChange https://toji.github.io/webgpu-clustered-shading/:166
```

**Comment by toji** [comment]
Yeah, Firefox compat is a known issue at this point. Their implementation is behind the spec a bit, though they're working on it! As a result so a lot of pages that use valid WebGPU calls  (as far as the specification is concerned) don't work there just yet.

I'm eagerly awaiting a point when they're more-or-less spec compliant, and when that day comes I'll happily fix any cross-browser bugs issues that may exist.
